# File: docs/environment.yaml

name: docs
channels:
  - conda-forge
  - defaults
dependencies:
  - sphinx==4.0.2
    #  - nbsphinx==0.8.1
  - pip:
    myst-parser==0.15.0
    # - sphinx_rtd_theme==0.5.1
